AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  StableBucket:
    Type: AWS::S3::Bucket

  UnstableBucket:
    Type: AWS::S3::Bucket

  TrailBucket:
    Type: AWS::S3::Bucket

  TrailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TrailBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Sid: AWSCloudTrailAclCheck
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: s3:GetBucketAcl
          Resource: !Sub "arn:aws:s3:::${TrailBucket}"
        - Sid: AWSCloudTrailWrite
          Effect: Allow
          Principal:
            Service: cloudtrail.amazonaws.com
          Action: 's3:PutObject'
          Resource: !Sub "arn:aws:s3:::${TrailBucket}/AWSLogs/${AWS::AccountId}/*"
          Condition:
            StringEquals:
              's3:x-amz-acl': 'bucket-owner-full-control'

  Trail:
    DependsOn:
      - TrailBucketPolicy
    Type: AWS::CloudTrail::Trail
    Properties: 
      EventSelectors: 
        - IncludeManagementEvents: false
          ReadWriteType: WriteOnly
          DataResources:
            - Type: AWS::S3::Object
              Values: 
                - !Sub "arn:aws:s3:::${UnstableBucket}/"
                - !Sub "arn:aws:s3:::${StableBucket}/"
      IsLogging: true
      S3BucketName: !Ref TrailBucket

Outputs:
  StableBucket:
    Value: !Ref StableBucket
  UnstableBucket:
    Value: !Ref UnstableBucket
  TrailBucket:
    Value: !Ref TrailBucket
