name: CI
on:
  push:
    branches:
    - master

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare Environment
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: npm ci
    - name: Test
      run: npm run test -- --coverage schema
    - name: Build
      run: npm run build
    - name: SAM Package
      uses: ./.github/actions/sam
      env:
        SAM_CLI_TELEMETRY: 0
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with: 
        args: >-
          package --template-file template.yaml 
          --output-template-file ${{ github.sha }}.yaml 
          --s3-bucket ${{ secrets.BUCKET }} 
          --s3-prefix ${{ github.repository }}/${{ github.sha }}
    - name: Push Template to S3
      uses: actions/aws/cli@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        args: >-
          s3 cp ./.aws-sam/build/${{ github.sha }}.yaml
          s3://${{ secrets.BUCKET }}/${{ github.repository }}/${{ github.sha }}/template.yaml

  # package:
  #   name: Package
  #   needs: test
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Prepare Environment
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: '10.x'
  #   - name: Run Build
  #     run: npm run build
    # - name: SAM Package
    #   working-directory: ./.aws-sam/build
    #   uses: actions/aws-sam
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   args:
    #     - package 
    #     - --template-file template.yaml
    #     - --output-template-file ${{ github.sha }}.yaml
    #     - --s3-bucket ${{ secrets.BUCKET }}

